source 'https://github.com/VerizonAdPlatforms/OneMobileSDK-releases-iOS.git'

target 'Tutorial' do
	platform :ios, 9.0
  	pod 'VerizonVideoPartnerSDK'
end

target 'Tutorial_tvOS' do
	platform :tvos, 9.0
  	pod 'VerizonVideoPartnerSDK'
end
