source 'https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-releases-iOS'

target 'Tutorial' do
	platform :ios, 9.0
  	pod 'VerizonVideoPartnerSDK', :path=>'../../'
end

target 'Tutorial_tvOS' do
	platform :tvos, 9.0
  	pod 'VerizonVideoPartnerSDK', :path=>'../../'
end
